export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_SIGNUP = "REQUEST_SIGNUP";
export const REQUEST_LOGIN_SUCCESSFULL = "REQUEST_LOGIN_SUCSESSFULL";
export const REQUEST_SIGNUP_SUSCESSFULL = "REQUEST_SIGNUP_SUCCESSFULL";
export const SET_REDIRECT_URL = "SET_REDIRECT_URL";